### ISSUE TITLE
问个问题(⊙o⊙)？

### ISSUE THREAD

**Issue by FF69B3** [HO-COOH/WinUIEssentials#2]
[bindable]
[default_interface] unsealed runtimeclass TextIconExtension : Microsoft.UI.Xaml.Markup.MarkupExtension
 {
     TextIconExtension();

     //Microsoft.UI.Xaml.Media.FontFamily SegoeMDL2AssetsFontFamily{ get; set; };

     Double FontSize{ get; set; };

     Windows.UI.Text.FontWeight FontWeight{ get; set; };

     Windows.UI.Text.FontStyle FontStyle{ get; set; };

     Microsoft.UI.Xaml.Media.Brush Foreground{ get; set; };

     Boolean IsTextScaleFactorEnabled{ get; set; };

     Boolean MirroredWhenRightToLeft{ get; set; };

};

[bindable]
[default_interface] unsealed runtimeclass FontIconExtension : TextIconExtension 
{
    FontIconExtension();

    String Glyph{ get; set; };

    Microsoft.UI.Xaml.Media.FontFamily FontFamily{ get; set; };

};

TextIconExtension 可以重写ProvideValue， 但是FontIconExtension  派生于TextIconExtension  无法重写ProvideValue。FontIconExtension  直接派生于Microsoft.UI.Xaml.Markup.MarkupExtension，也是可以重写的，我是从WindowsCommunityToolkit 库 copy 过来的，有啥解决办法吗？

**Comment by HO-COOH** [comment]
一个方法应该只能被重写一次的，我看了下Community Toolkit，它的`TextIconExtension`并没有重写`ProvideValue`呀，所以它是个abstract类，在C++WinRT里应该相当于是，你只新建一个idl文件（不带.h和.cpp）的那种，把要共享的属性定义在里面，然后声名为interface，而不是runtimeclass，然后在要重写ProvideValue的实际类里继承这个interface，[我这有个例子](https://github.com/HO-COOH/FastCopy/blob/master/FastCopy/ICopyBase.idl)

**Comment by FF69B3** [comment]
嗯，我目前遇到情况就是派生于 Microsoft.UI.Xaml.Markup.MarkupExtension 时 ProvideValue 函数只能被TextIconExtension 重写，
TextIconExtension 里我没有重写ProvideValue , FontIconExtension派生于TextIconExtension时， 重写了ProvideValue 也是没有用的，有点没搞清楚。

**Comment by FF69B3** [comment]
根据你的指点哈，
`
interface TextIconExtension
{
    Double FontSize{ get; set; };

   Windows.UI.Text.FontWeight FontWeight{ get; set; };

   Windows.UI.Text.FontStyle FontStyle{ get; set; };

   Microsoft.UI.Xaml.Media.Brush Foreground{ get; set; };

   Boolean IsTextScaleFactorEnabled{ get; set; };

   Boolean MirroredWhenRightToLeft{ get; set; };
}`
  [bindable]
  [default_interface] unsealed runtimeclass FontIconExtension : Microsoft.UI.Xaml.Markup.MarkupExtension, TextIconExtension
  {
}
这样是可以用的，但是实际上TextIconExtension 里的属性还是得在 派生的类的里手动去实现，感觉不是C#那样的那样实现方式，在研究研究。

**Comment by HO-COOH** [comment]
又仔细看了一遍文档，发现人家[早写了](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#overriding-base-class-virtual-methods)😭（
所以你还是让`TextIconExtension`继承`Microsoft.UI.Xaml.Markup.MarkupExtension`，然后让`FontIconExtension`继承`TextIconExtension`，但是`TextIconExtension`里的`ProvideValue`声明成`virtual`的，另外注意下在.h文件里
```cpp
#include "TextIconExtension.h" //加上这个include
struct FontIconExtension : FontIconExtensionT<FontIconExtension, TextIconExtension>
{ ... };
```

**Comment by FF69B3** [comment]
@HO-COOH   感谢大佬相助，绕了个大弯，搞了大半天原来就差一个virtual。我一直看的是MIDL 3.0接口的文档，搞错方向了，头疼头疼，好在还是解决了。
